FROM node:22-alpine3.21 AS deps
WORKDIR /app
COPY package.json ./
RUN npm install

FROM node:22-alpine3.21 AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ARG NEXT_PUBLIC_API_URL=https://chessbackend-production-7a57.up.railway.app
ARG NEXT_PUBLIC_WS_URL=wss://chessbackend-production-7a57.up.railway.app
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_WS_URL=$NEXT_PUBLIC_WS_URL

# Firebase web config (public client keys — safe to bake into the build).
ARG NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyC9iXhGOGgpk69rfo4RToSjCLoInzHDg3o
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=fianchess.firebaseapp.com
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID=fianchess
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=fianchess.firebasestorage.app
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=881974706411
ARG NEXT_PUBLIC_FIREBASE_APP_ID=1:881974706411:web:5baaf806915a2eaa7ebeae
ARG NEXT_PUBLIC_FIREBASE_VAPID_KEY=BOQbMdFwULR4emYVQcLYkolfbvAs_5YoCcBB8ZO41VS6U-RYEoE61YMiiiwD68rUkny1wY53T8-aTNtoF6lcGR4
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_FIREBASE_VAPID_KEY=$NEXT_PUBLIC_FIREBASE_VAPID_KEY

RUN npm run build

FROM node:22-alpine3.21 AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/public ./public
EXPOSE 3000
CMD ["npm", "start"]
